# Generated by Django 4.2.20 on 2025-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Кг'), ('pcs', 'Шт.'), ('ml', 'Мл.')], default='pcs', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_value',
            field=models.FloatField(default=1.0),
        ),
    ]
