# Generated by Django 4.2.20 on 2025-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_quantity_unit_product_quantity_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='unique_product_per_store'),
        ),
    ]
