# Generated by Django 4.2.20 on 2025-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_price_unique_product_per_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Кг'), ('pcs', 'Шт.'), ('ml', 'Мл.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_value',
            field=models.FloatField(),
        ),
    ]
