# Generated by Django 4.2.20 on 2025-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_quantity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_value',
            field=models.FloatField(max_length=10),
        ),
    ]
