# Generated by Django 4.2.20 on 2025-05-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Product_Category',
        ),
    ]
