# Generated by Django 4.2.20 on 2025-05-12 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='store',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('owner', 'Владелец магазина'), ('admin', 'Администратор')], default='user', max_length=10),
        ),
    ]
