# Generated by Django 4.2.20 on 2025-05-14 07:39

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_user_is_admin_store_owners_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no-photo.png', null=True, upload_to=catalog.models.product_image_path),
        ),
    ]
