# Generated by Django 4.2.20 on 2025-05-14 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_manufacturer_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
