# Generated by Django 4.2.20 on 2025-05-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_store_owners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Category',
            new_name='ProductCategory',
        ),
    ]
