# Generated by Django 4.2.20 on 2025-05-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_product_category_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.AddField(
            model_name='store',
            name='house_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AddressBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Курчатов', max_length=100)),
                ('street', models.CharField(max_length=150)),
            ],
            options={
                'unique_together': {('city', 'street')},
            },
        ),
        migrations.AddField(
            model_name='store',
            name='address_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.addressbase'),
        ),
    ]
