# Generated by Django 4.2.20 on 2025-06-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_user_avatar_alter_user_role_productsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsuggestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsuggestion',
            name='store',
        ),
        migrations.AddField(
            model_name='productsuggestion',
            name='category_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsuggestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suggestions/'),
        ),
        migrations.AddField(
            model_name='productsuggestion',
            name='store_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
